### ISSUE TITLE
python3-11-x86-64-layer-builder not packaging the right files

### ISSUE THREAD

**Issue by arya-coding** [peterjdavis/python-layer-builder#1]
Hi there,

Nice concept, I'm surprised this didn't existed before.

I tried the serverlessrepo-python3-11-x86-64-layer-builder. Deployed through console. Haven't tried through SAM yet.

LayerName : Whatever
LayerPackages : requests

I'm having the following content in the layer zip created by your lambda function : 
python folder at root (so that's good), but inside : 
![image](https://github.com/peterjdavis/python-layer-builder/assets/9800251/29b25bad-b222-4c5b-93ed-221195424efb)

However, I can find the packages in your zip at the following path : \python\lib\python3.11\site-packages

Regards

**Comment by arya-coding** [comment]
https://github.com/peterjdavis/python-layer-builder/pull/2#issue-2040413167

**Comment by arya-coding** [comment]
[Pull request Issue #1 - Refined ZIP Creation #2 ](https://github.com/peterjdavis/python-layer-builder/pull/2#issue-2040413167)

**Comment by peterjdavis** [comment]
Hi, thanks for trying this out (I'm surprised it doesn't already exist as well :-) )

Where are you expecting the package to exist in the tree, in my testing everything has worked as expected with the package in the \python\lib\python3.11\site-packages folder?

**Comment by arya-coding** [comment]
No thanks to you trying to make the lambda experience better. I wished there was a console button interfaced with Pypi directly.

I did a typo in the LayerPackages, wrote "request" and not "requests". I would have spot that easier by using SAM. Will try that out.

Is there a way to output the pip error (or logs) to the user ? Maybe in the S3 as .txt ?

**Comment by peterjdavis** [comment]
Hi, the logs (including the pip output) are written to CloudWatch logs in a log group named the same as the SAR application.  See below for output if I try to create a layer with the package `request`.  I'll have a look at what would be involved in creating a CloudWatch alarm to notify the user if any errors reported.

<img width="1048" alt="image" src="https://github.com/peterjdavis/python-layer-builder/assets/1465660/40242140-b9be-4078-bed8-184f345e1e8c">

**Comment by arya-coding** [comment]
Perfect, thank you Peter, will try it out through cloud formation now.

**Comment by peterjdavis** [comment]
Cool, let me know how you get on.  

Is there any value in the PR you submitted now?  Thanks for taking the time to create this.

**Comment by arya-coding** [comment]
Unfortunately, no. My solution requires one more copy operation (with many small Python files of the installed libs), so it will take more compute time and cost.

However, I'm thinking of submitting a PR to rename the zip layer with a short title of the pip error if the user inputs are incorrect (or a simple error_building_layers_check_cloudwatch.zip). Because intuitively, when I saw the .zip available in layers, I thought it was built fine, without suspecting a typo. PEBCAK.
